# Copyright 2021 Kidus Tiliksew

# This file is part of Tensor EMR.

# Tensor EMR is free software: you can redistribute it and/or modify
# it under the terms of the version 2 of GNU General Public License as published by
# the Free Software Foundation.

# Tensor EMR is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: "3.2"

services:
  backend:
    image: ghcr.io/tensor-systems/tensoremr-server:main
    ports:
      - "8080:8080"
    volumes:
      - backendfiles:/files
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_NAME: "emr"
      DB_HOST: "localhost"
      #      DB_REPLICATION_HOST: "192.168.1.101"
      DB_DRIVER: "postgres"
      DB_PORT: 5432
      RXNORM_ADDRESS: "https://rxnav.nlm.nih.gov"
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - emr

  webclient:
    image: ghcr.io/tensor-systems/emr-webclient:main
    ports:
      - "80:80"
    environment:
      NODE_ENV: "production"
      REACT_APP_SERVER_URL: http://localhost:8080
      REACT_APP_ELASTICSEARCH_URL: http://localhost:9200
    depends_on:
      - backend
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - emr

  

  # queue:
  #   image: ghcr.io/tensor-systems/emr-queue:main
  #   ports:
  #     - "8095:8095"
  #   environment:
  #     NODE_ENV: "production"
  #     REACT_APP_SERVER_URL: http://localhost:8080
  #     REACT_APP_ELASTICSEARCH_URL: http://localhost:9200
  #   depends_on:
  #     - backend
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   networks:
  #     - emr

volumes:
  elasticsearch:
  postgres:
  backendfiles:

networks:
  emr:
    driver: overlay
